import Head from 'next/head'
import Navbar from '../Components/Navbar'
import HomeLayout from '../layouts/HomeLayout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full flex flex-col items-center justify-center' >
        Jai ho
      </main>
    </div>
  )
}

Home.Layout = HomeLayout